# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postprocesing.ui'
#
# Created: Fri Jan 10 12:37:01 2014
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(896, 1040)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.button_exit = QtGui.QPushButton(self.groupBox)
        self.button_exit.setObjectName(_fromUtf8("button_exit"))
        self.horizontalLayout.addWidget(self.button_exit)
        self.button_quick_test = QtGui.QPushButton(self.groupBox)
        self.button_quick_test.setObjectName(_fromUtf8("button_quick_test"))
        self.horizontalLayout.addWidget(self.button_quick_test)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.element_selector = QtGui.QWidget()
        self.element_selector.setObjectName(_fromUtf8("element_selector"))
        self.gridLayout_5 = QtGui.QGridLayout(self.element_selector)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mesh_control = QtGui.QGroupBox(self.element_selector)
        self.mesh_control.setObjectName(_fromUtf8("mesh_control"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mesh_control)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.select_mesh_mtr = QtGui.QComboBox(self.groupBox_5)
        self.select_mesh_mtr.setObjectName(_fromUtf8("select_mesh_mtr"))
        self.horizontalLayout_5.addWidget(self.select_mesh_mtr)
        self.button_mesh_import_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_import_mtr.setObjectName(_fromUtf8("button_mesh_import_mtr"))
        self.horizontalLayout_5.addWidget(self.button_mesh_import_mtr)
        self.button_mesh_remove_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_remove_mtr.setObjectName(_fromUtf8("button_mesh_remove_mtr"))
        self.horizontalLayout_5.addWidget(self.button_mesh_remove_mtr)
        self.gridLayout_3.addWidget(self.groupBox_5, 2, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.groupBox1 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.mesh_radio_x = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_x.setMaximumSize(QtCore.QSize(76, 16777215))
        self.mesh_radio_x.setObjectName(_fromUtf8("mesh_radio_x"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_x)
        self.mesh_radio_y = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_y.setObjectName(_fromUtf8("mesh_radio_y"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_y)
        self.mesh_radio_z = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_z.setObjectName(_fromUtf8("mesh_radio_z"))
        self.horizontalLayout_4.addWidget(self.mesh_radio_z)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_11)
        self.button_mesh_imp_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_over.setObjectName(_fromUtf8("button_mesh_imp_over"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.button_mesh_imp_over)
        self.button_mesh_rem_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_over.setObjectName(_fromUtf8("button_mesh_rem_over"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.button_mesh_rem_over)
        self.button_mesh_imp_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_bellow.setObjectName(_fromUtf8("button_mesh_imp_bellow"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.button_mesh_imp_bellow)
        self.button_mesh_rem_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_bellow.setObjectName(_fromUtf8("button_mesh_rem_bellow"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.button_mesh_rem_bellow)
        self.button_mesh_imp_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_through.setObjectName(_fromUtf8("button_mesh_imp_through"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.button_mesh_imp_through)
        self.button_mesh_rem_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_through.setObjectName(_fromUtf8("button_mesh_rem_through"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.button_mesh_rem_through)
        self.button_mesh_imp_surface = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_surface.setObjectName(_fromUtf8("button_mesh_imp_surface"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.button_mesh_imp_surface)
        self.button_mesh_imp_nonzero = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_nonzero.setObjectName(_fromUtf8("button_mesh_imp_nonzero"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.button_mesh_imp_nonzero)
        self.button_mesh_remove_zero = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_remove_zero.setObjectName(_fromUtf8("button_mesh_remove_zero"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.button_mesh_remove_zero)
        self.edit_mesh_crd = QtGui.QLineEdit(self.groupBox_4)
        self.edit_mesh_crd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_mesh_crd.setObjectName(_fromUtf8("edit_mesh_crd"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.edit_mesh_crd)
        self.gridLayout_3.addWidget(self.groupBox_4, 5, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 11, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_3.setMinimumSize(QtCore.QSize(222, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mesh_element_id_edit = QtGui.QLineEdit(self.groupBox_3)
        self.mesh_element_id_edit.setMaximumSize(QtCore.QSize(50, 30))
        self.mesh_element_id_edit.setObjectName(_fromUtf8("mesh_element_id_edit"))
        self.horizontalLayout_3.addWidget(self.mesh_element_id_edit)
        self.button_mesh_imp_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_imp_elmid.setObjectName(_fromUtf8("button_mesh_imp_elmid"))
        self.horizontalLayout_3.addWidget(self.button_mesh_imp_elmid)
        self.button_mesh_rem_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_rem_elmid.setObjectName(_fromUtf8("button_mesh_rem_elmid"))
        self.horizontalLayout_3.addWidget(self.button_mesh_rem_elmid)
        self.gridLayout_3.addWidget(self.groupBox_3, 9, 0, 1, 2)
        self.frame_5 = QtGui.QFrame(self.mesh_control)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.button_mesh_import_all = QtGui.QPushButton(self.frame_5)
        self.button_mesh_import_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_import_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_import_all.setObjectName(_fromUtf8("button_mesh_import_all"))
        self.horizontalLayout_8.addWidget(self.button_mesh_import_all)
        self.button_mesh_remove_all = QtGui.QPushButton(self.frame_5)
        self.button_mesh_remove_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_remove_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_remove_all.setObjectName(_fromUtf8("button_mesh_remove_all"))
        self.horizontalLayout_8.addWidget(self.button_mesh_remove_all)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.mesh_control, 0, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.element_selector)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_6)
        self.groupBox_2.setMinimumSize(QtCore.QSize(328, 543))
        self.groupBox_2.setMaximumSize(QtCore.QSize(2000, 3000))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.mesh_list = QtGui.QListWidget(self.groupBox_2)
        self.mesh_list.setObjectName(_fromUtf8("mesh_list"))
        self.verticalLayout_4.addWidget(self.mesh_list)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(self.frame_6)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mesh_element_explorer = QtGui.QPlainTextEdit(self.groupBox_6)
        self.mesh_element_explorer.setObjectName(_fromUtf8("mesh_element_explorer"))
        self.gridLayout_7.addWidget(self.mesh_element_explorer, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.gridLayout_5.addWidget(self.frame_6, 0, 1, 1, 1)
        self.tabWidget.addTab(self.element_selector, _fromUtf8(""))
        self.basic_analyser = QtGui.QWidget()
        self.basic_analyser.setObjectName(_fromUtf8("basic_analyser"))
        self.verticalLayout = QtGui.QVBoxLayout(self.basic_analyser)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.basic_analyser)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.groupBox_31 = QtGui.QGroupBox(self.basic_analyser)
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_31)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.button_draw_charts = QtGui.QPushButton(self.groupBox_31)
        self.button_draw_charts.setObjectName(_fromUtf8("button_draw_charts"))
        self.gridLayout_4.addWidget(self.button_draw_charts, 1, 1, 1, 1)
        self.button_save_tables = QtGui.QPushButton(self.groupBox_31)
        self.button_save_tables.setObjectName(_fromUtf8("button_save_tables"))
        self.gridLayout_4.addWidget(self.button_save_tables, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_31)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.edit_chart_min_conc = QtGui.QLineEdit(self.groupBox_31)
        self.edit_chart_min_conc.setMaximumSize(QtCore.QSize(100, 16777215))
        self.edit_chart_min_conc.setObjectName(_fromUtf8("edit_chart_min_conc"))
        self.gridLayout_4.addWidget(self.edit_chart_min_conc, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_31)
        self.groupBox_7 = QtGui.QGroupBox(self.basic_analyser)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.maps_sim_time_select = QtGui.QComboBox(self.groupBox_7)
        self.maps_sim_time_select.setObjectName(_fromUtf8("maps_sim_time_select"))
        self.gridLayout_2.addWidget(self.maps_sim_time_select, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 4, 1, 1)
        self.maps_radio_surface = QtGui.QRadioButton(self.groupBox_7)
        self.maps_radio_surface.setObjectName(_fromUtf8("maps_radio_surface"))
        self.gridLayout_2.addWidget(self.maps_radio_surface, 0, 0, 1, 1)
        self.maps_radio_section = QtGui.QRadioButton(self.groupBox_7)
        self.maps_radio_section.setAccessibleName(_fromUtf8(""))
        self.maps_radio_section.setObjectName(_fromUtf8("maps_radio_section"))
        self.gridLayout_2.addWidget(self.maps_radio_section, 0, 1, 1, 1)
        self.button_draw_maps = QtGui.QPushButton(self.groupBox_7)
        self.button_draw_maps.setObjectName(_fromUtf8("button_draw_maps"))
        self.gridLayout_2.addWidget(self.button_draw_maps, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.maps_check_nonzero = QtGui.QCheckBox(self.groupBox_7)
        self.maps_check_nonzero.setObjectName(_fromUtf8("maps_check_nonzero"))
        self.gridLayout_2.addWidget(self.maps_check_nonzero, 1, 0, 1, 1)
        self.maps_section_height = QtGui.QLineEdit(self.groupBox_7)
        self.maps_section_height.setMaximumSize(QtCore.QSize(50, 16777215))
        self.maps_section_height.setObjectName(_fromUtf8("maps_section_height"))
        self.gridLayout_2.addWidget(self.maps_section_height, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.label_basic_1 = QtGui.QLabel(self.basic_analyser)
        self.label_basic_1.setObjectName(_fromUtf8("label_basic_1"))
        self.verticalLayout.addWidget(self.label_basic_1)
        self.label_basic_2 = QtGui.QLabel(self.basic_analyser)
        self.label_basic_2.setObjectName(_fromUtf8("label_basic_2"))
        self.verticalLayout.addWidget(self.label_basic_2)
        self.groupBox_8 = QtGui.QGroupBox(self.basic_analyser)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edit_chart_x_text = QtGui.QLineEdit(self.groupBox_8)
        self.edit_chart_x_text.setStatusTip(_fromUtf8(""))
        self.edit_chart_x_text.setObjectName(_fromUtf8("edit_chart_x_text"))
        self.gridLayout.addWidget(self.edit_chart_x_text, 0, 1, 1, 1)
        self.edit_chart_y_text = QtGui.QLineEdit(self.groupBox_8)
        self.edit_chart_y_text.setObjectName(_fromUtf8("edit_chart_y_text"))
        self.gridLayout.addWidget(self.edit_chart_y_text, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.edit_chart_title_text = QtGui.QLineEdit(self.groupBox_8)
        self.edit_chart_title_text.setObjectName(_fromUtf8("edit_chart_title_text"))
        self.gridLayout.addWidget(self.edit_chart_title_text, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.tabWidget.addTab(self.basic_analyser, _fromUtf8(""))
        self.comparative_analyser = QtGui.QWidget()
        self.comparative_analyser.setObjectName(_fromUtf8("comparative_analyser"))
        self.gridLayout_10 = QtGui.QGridLayout(self.comparative_analyser)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_analyser_title = QtGui.QLabel(self.comparative_analyser)
        self.label_analyser_title.setMaximumSize(QtCore.QSize(584, 16777215))
        self.label_analyser_title.setObjectName(_fromUtf8("label_analyser_title"))
        self.gridLayout_10.addWidget(self.label_analyser_title, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.comparative_analyser)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.box_sensitivity = QtGui.QGroupBox(self.frame)
        self.box_sensitivity.setMinimumSize(QtCore.QSize(0, 186))
        self.box_sensitivity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.box_sensitivity.setObjectName(_fromUtf8("box_sensitivity"))
        self.formLayout = QtGui.QFormLayout(self.box_sensitivity)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.radio_compare_all = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_all.setChecked(True)
        self.radio_compare_all.setObjectName(_fromUtf8("radio_compare_all"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.radio_compare_all)
        self.radio_compare_surface = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_surface.setObjectName(_fromUtf8("radio_compare_surface"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.radio_compare_surface)
        self.radio_compare_selected = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_selected.setObjectName(_fromUtf8("radio_compare_selected"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.radio_compare_selected)
        self.check_compare_sum = QtGui.QCheckBox(self.box_sensitivity)
        self.check_compare_sum.setObjectName(_fromUtf8("check_compare_sum"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.check_compare_sum)
        self.horizontalLayout_7.addWidget(self.box_sensitivity)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.button_compare = QtGui.QPushButton(self.frame_4)
        self.button_compare.setObjectName(_fromUtf8("button_compare"))
        self.verticalLayout_5.addWidget(self.button_compare)
        self.button_export_csv = QtGui.QPushButton(self.frame_4)
        self.button_export_csv.setObjectName(_fromUtf8("button_export_csv"))
        self.verticalLayout_5.addWidget(self.button_export_csv)
        self.spin_grade_filter = QtGui.QSpinBox(self.frame_4)
        self.spin_grade_filter.setObjectName(_fromUtf8("spin_grade_filter"))
        self.verticalLayout_5.addWidget(self.spin_grade_filter)
        self.button_grade_filter = QtGui.QPushButton(self.frame_4)
        self.button_grade_filter.setObjectName(_fromUtf8("button_grade_filter"))
        self.verticalLayout_5.addWidget(self.button_grade_filter)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.box_merger = QtGui.QGroupBox(self.frame)
        self.box_merger.setObjectName(_fromUtf8("box_merger"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.box_merger)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.button_merge = QtGui.QPushButton(self.box_merger)
        self.button_merge.setObjectName(_fromUtf8("button_merge"))
        self.verticalLayout_6.addWidget(self.button_merge)
        self.label = QtGui.QLabel(self.box_merger)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_6.addWidget(self.label)
        self.edit_merge_minval = QtGui.QLineEdit(self.box_merger)
        self.edit_merge_minval.setObjectName(_fromUtf8("edit_merge_minval"))
        self.verticalLayout_6.addWidget(self.edit_merge_minval)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_7.addWidget(self.box_merger)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.gridLayout_10.addWidget(self.frame, 5, 0, 1, 1)
        self.table_comp_rslt = QtGui.QTableView(self.comparative_analyser)
        self.table_comp_rslt.setObjectName(_fromUtf8("table_comp_rslt"))
        self.gridLayout_10.addWidget(self.table_comp_rslt, 6, 0, 1, 1)
        self.tabWidget.addTab(self.comparative_analyser, _fromUtf8(""))
        self.data_processing = QtGui.QWidget()
        self.data_processing.setObjectName(_fromUtf8("data_processing"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.data_processing)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_71 = QtGui.QGroupBox(self.data_processing)
        self.groupBox_71.setObjectName(_fromUtf8("groupBox_71"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_71)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_processing_text = QtGui.QLabel(self.groupBox_71)
        self.label_processing_text.setObjectName(_fromUtf8("label_processing_text"))
        self.verticalLayout_3.addWidget(self.label_processing_text)
        self.frame_2 = QtGui.QFrame(self.groupBox_71)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.button_process_all = QtGui.QPushButton(self.frame_2)
        self.button_process_all.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_process_all.setObjectName(_fromUtf8("button_process_all"))
        self.horizontalLayout_6.addWidget(self.button_process_all)
        self.button_process_newonly = QtGui.QPushButton(self.frame_2)
        self.button_process_newonly.setMaximumSize(QtCore.QSize(1666666, 1666666))
        self.button_process_newonly.setObjectName(_fromUtf8("button_process_newonly"))
        self.horizontalLayout_6.addWidget(self.button_process_newonly)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.progress_processing = QtGui.QProgressBar(self.groupBox_71)
        self.progress_processing.setProperty("value", 24)
        self.progress_processing.setObjectName(_fromUtf8("progress_processing"))
        self.verticalLayout_3.addWidget(self.progress_processing)
        self.verticalLayout_2.addWidget(self.groupBox_71)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.tabWidget.addTab(self.data_processing, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.tabWidget)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 896, 27))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_Ini_File = QtGui.QMenu(self.menuBar)
        self.menu_Ini_File.setObjectName(_fromUtf8("menu_Ini_File"))
        self.menuSo_lve = QtGui.QMenu(self.menuBar)
        self.menuSo_lve.setObjectName(_fromUtf8("menuSo_lve"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action_Basic_problem = QtGui.QAction(MainWindow)
        self.action_Basic_problem.setObjectName(_fromUtf8("action_Basic_problem"))
        self.action_Generate_materials = QtGui.QAction(MainWindow)
        self.action_Generate_materials.setObjectName(_fromUtf8("action_Generate_materials"))
        self.action_Quick_Test = QtGui.QAction(MainWindow)
        self.action_Quick_Test.setObjectName(_fromUtf8("action_Quick_Test"))
        self.actionSave_Material = QtGui.QAction(MainWindow)
        self.actionSave_Material.setObjectName(_fromUtf8("actionSave_Material"))
        self.actionExit_program = QtGui.QAction(MainWindow)
        self.actionExit_program.setObjectName(_fromUtf8("actionExit_program"))
        self.actionSensitivity_task = QtGui.QAction(MainWindow)
        self.actionSensitivity_task.setObjectName(_fromUtf8("actionSensitivity_task"))
        self.actionMonte_Carlo = QtGui.QAction(MainWindow)
        self.actionMonte_Carlo.setObjectName(_fromUtf8("actionMonte_Carlo"))
        self.menu_Ini_File.addAction(self.action_Open)
        self.menu_Ini_File.addAction(self.action_Close)
        self.menu_Ini_File.addAction(self.action_Save)
        self.menu_Ini_File.addSeparator()
        self.menu_Ini_File.addAction(self.actionExit)
        self.menuSo_lve.addAction(self.action_Basic_problem)
        self.menuSo_lve.addAction(self.actionSensitivity_task)
        self.menuSo_lve.addAction(self.actionMonte_Carlo)
        self.menuTools.addAction(self.action_Quick_Test)
        self.menuTools.addAction(self.actionSave_Material)
        self.menuTools.addAction(self.actionExit_program)
        self.menuBar.addAction(self.menu_Ini_File.menuAction())
        self.menuBar.addAction(self.menuSo_lve.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Postprocessor RiskFlow123D", None))
        self.button_exit.setText(_translate("MainWindow", "Exit", None))
        self.button_quick_test.setToolTip(_translate("MainWindow", "Open last problem", None))
        self.button_quick_test.setWhatsThis(_translate("MainWindow", "Open last problem", None))
        self.button_quick_test.setText(_translate("MainWindow", "Quick Start", None))
        self.tabWidget.setToolTip(_translate("MainWindow", "Flow.ini check and editor", None))
        self.mesh_control.setTitle(_translate("MainWindow", "Import elements", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Element Material", None))
        self.button_mesh_import_mtr.setText(_translate("MainWindow", "Import MTR", None))
        self.button_mesh_remove_mtr.setText(_translate("MainWindow", "Remove MTR", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Element Position", None))
        self.groupBox1.setTitle(_translate("MainWindow", "Axis", None))
        self.mesh_radio_x.setText(_translate("MainWindow", "X", None))
        self.mesh_radio_y.setText(_translate("MainWindow", "Y", None))
        self.mesh_radio_z.setText(_translate("MainWindow", "Z", None))
        self.label_11.setText(_translate("MainWindow", "Axis coordinate", None))
        self.button_mesh_imp_over.setToolTip(_translate("MainWindow", "Import all elements with altitude over set height", None))
        self.button_mesh_imp_over.setText(_translate("MainWindow", "Import Over ", None))
        self.button_mesh_rem_over.setText(_translate("MainWindow", "Remove Over", None))
        self.button_mesh_imp_bellow.setText(_translate("MainWindow", "Import Bellow", None))
        self.button_mesh_rem_bellow.setText(_translate("MainWindow", "Remove Bellow", None))
        self.button_mesh_imp_through.setText(_translate("MainWindow", "Import through", None))
        self.button_mesh_rem_through.setText(_translate("MainWindow", "Remove Through", None))
        self.button_mesh_imp_surface.setText(_translate("MainWindow", "Import Surface ", None))
        self.button_mesh_imp_nonzero.setText(_translate("MainWindow", "Import NonZero", None))
        self.button_mesh_remove_zero.setText(_translate("MainWindow", "Remove Zero", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Element ID", None))
        self.button_mesh_imp_elmid.setText(_translate("MainWindow", "Import", None))
        self.button_mesh_rem_elmid.setText(_translate("MainWindow", "Remove", None))
        self.button_mesh_import_all.setText(_translate("MainWindow", "Import All", None))
        self.button_mesh_remove_all.setText(_translate("MainWindow", "Remove All", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "0 elemets in the list", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Element explorer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.element_selector), _translate("MainWindow", "Element Selector", None))
        self.label_3.setText(_translate("MainWindow", "Basic Problem Analyser", None))
        self.groupBox_31.setTitle(_translate("MainWindow", "Concentration  on selected elements in time", None))
        self.button_draw_charts.setToolTip(_translate("MainWindow", "Draw chart of contentrations", None))
        self.button_draw_charts.setWhatsThis(_translate("MainWindow", "Draw chart of contentrations", None))
        self.button_draw_charts.setText(_translate("MainWindow", "Draw Charts", None))
        self.button_save_tables.setToolTip(_translate("MainWindow", "Save CSV tables with concentrations on selected elements", None))
        self.button_save_tables.setWhatsThis(_translate("MainWindow", "Save CSV tables with concentrations on selected elements", None))
        self.button_save_tables.setText(_translate("MainWindow", "Save Tables", None))
        self.label_7.setText(_translate("MainWindow", "minimal conc.", None))
        self.edit_chart_min_conc.setToolTip(_translate("MainWindow", "Use only solutions where concetration is greater than given minimal value", None))
        self.edit_chart_min_conc.setWhatsThis(_translate("MainWindow", "Use only solutions where concetration is greater than given minimal value", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Concentration maps", None))
        self.maps_sim_time_select.setToolTip(_translate("MainWindow", "time of simulation step", None))
        self.maps_sim_time_select.setStatusTip(_translate("MainWindow", "time of simulation step", None))
        self.maps_sim_time_select.setWhatsThis(_translate("MainWindow", "time of simulation step", None))
        self.maps_radio_surface.setToolTip(_translate("MainWindow", "surface elements", None))
        self.maps_radio_surface.setStatusTip(_translate("MainWindow", "map of concentrations on surface elements", None))
        self.maps_radio_surface.setWhatsThis(_translate("MainWindow", "map of concentrations on surface elements", None))
        self.maps_radio_surface.setText(_translate("MainWindow", "surface", None))
        self.maps_radio_section.setToolTip(_translate("MainWindow", "map of concentrations on given height ", None))
        self.maps_radio_section.setStatusTip(_translate("MainWindow", "map of concentrations on given height ", None))
        self.maps_radio_section.setWhatsThis(_translate("MainWindow", "map of concentrations on given height ", None))
        self.maps_radio_section.setText(_translate("MainWindow", "section height", None))
        self.button_draw_maps.setToolTip(_translate("MainWindow", "draw map", None))
        self.button_draw_maps.setText(_translate("MainWindow", "Draw Maps", None))
        self.label_6.setText(_translate("MainWindow", "Simulation time", None))
        self.maps_check_nonzero.setToolTip(_translate("MainWindow", "only elements with non zero concentration", None))
        self.maps_check_nonzero.setStatusTip(_translate("MainWindow", "only elements with non zero concentration", None))
        self.maps_check_nonzero.setWhatsThis(_translate("MainWindow", "only elements with non zero concentration", None))
        self.maps_check_nonzero.setText(_translate("MainWindow", "non-zero only", None))
        self.maps_section_height.setToolTip(_translate("MainWindow", "height ", None))
        self.maps_section_height.setStatusTip(_translate("MainWindow", "height ", None))
        self.maps_section_height.setWhatsThis(_translate("MainWindow", "height ", None))
        self.label_basic_1.setText(_translate("MainWindow", "Found 1000 elements with non-zero concentrations.", None))
        self.label_basic_2.setText(_translate("MainWindow", "5 elements selected for chart draw.", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Chart settings", None))
        self.edit_chart_x_text.setToolTip(_translate("MainWindow", "Change text for X axis of the chart", None))
        self.edit_chart_x_text.setWhatsThis(_translate("MainWindow", "Change text for X axis of the chart", None))
        self.edit_chart_y_text.setToolTip(_translate("MainWindow", "Change text for Y axis of the chart", None))
        self.edit_chart_y_text.setWhatsThis(_translate("MainWindow", "Change text for Y axis of the chart", None))
        self.label_2.setText(_translate("MainWindow", "Axis X text", None))
        self.edit_chart_title_text.setToolTip(_translate("MainWindow", "Change title text for the chart", None))
        self.edit_chart_title_text.setWhatsThis(_translate("MainWindow", "Change title text for the chart", None))
        self.label_5.setText(_translate("MainWindow", "Title", None))
        self.label_4.setText(_translate("MainWindow", "Axis Y text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic_analyser), _translate("MainWindow", "Basic  Analyser", None))
        self.label_analyser_title.setText(_translate("MainWindow", " Monte Carlo, Sensitivity Task", None))
        self.box_sensitivity.setTitle(_translate("MainWindow", "Compare with original task", None))
        self.radio_compare_all.setText(_translate("MainWindow", "All", None))
        self.radio_compare_surface.setText(_translate("MainWindow", "Surface", None))
        self.radio_compare_selected.setText(_translate("MainWindow", "Selected ", None))
        self.check_compare_sum.setText(_translate("MainWindow", "Sum of Concentrations", None))
        self.button_compare.setText(_translate("MainWindow", "Start comparsion", None))
        self.button_export_csv.setText(_translate("MainWindow", "Export to CSV", None))
        self.button_grade_filter.setText(_translate("MainWindow", "Filter grade", None))
        self.box_merger.setTitle(_translate("MainWindow", "Merge data", None))
        self.button_merge.setText(_translate("MainWindow", "Merge Files", None))
        self.label.setText(_translate("MainWindow", "minimal value", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comparative_analyser), _translate("MainWindow", "Comparative Analyser", None))
        self.groupBox_71.setTitle(_translate("MainWindow", "Data", None))
        self.label_processing_text.setText(_translate("MainWindow", "Found 320 tasks to analyze. Data processing will cost aprox. 90 minutes.", None))
        self.button_process_all.setText(_translate("MainWindow", "All", None))
        self.button_process_newonly.setText(_translate("MainWindow", "Unprocessed only", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_processing), _translate("MainWindow", "Data processing", None))
        self.menu_Ini_File.setTitle(_translate("MainWindow", "&Task File", None))
        self.menuSo_lve.setTitle(_translate("MainWindow", "Analyser type", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))
        self.action_Save.setText(_translate("MainWindow", "&Save", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.action_Basic_problem.setText(_translate("MainWindow", "&Basic problem", None))
        self.action_Generate_materials.setText(_translate("MainWindow", "&Generate materials", None))
        self.action_Quick_Test.setText(_translate("MainWindow", "&Quick Test", None))
        self.actionSave_Material.setText(_translate("MainWindow", "Save Material", None))
        self.actionExit_program.setText(_translate("MainWindow", "Exit program", None))
        self.actionSensitivity_task.setText(_translate("MainWindow", "Sensitivity task", None))
        self.actionMonte_Carlo.setText(_translate("MainWindow", "Monte Carlo", None))

