# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postprocesing.ui'
#
# Created: Thu Aug 30 11:01:12 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 870)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 601, 56))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_exit = QtGui.QPushButton(self.groupBox)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout.addWidget(self.button_exit)
        self.button_quick_test = QtGui.QPushButton(self.groupBox)
        self.button_quick_test.setObjectName("button_quick_test")
        self.horizontalLayout.addWidget(self.button_quick_test)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(9, 71, 608, 791))
        self.tabWidget.setMaximumSize(QtCore.QSize(608, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mesh_control = QtGui.QGroupBox(self.tab_1)
        self.mesh_control.setMinimumSize(QtCore.QSize(250, 527))
        self.mesh_control.setMaximumSize(QtCore.QSize(250, 16777215))
        self.mesh_control.setObjectName("mesh_control")
        self.gridLayout_3 = QtGui.QGridLayout(self.mesh_control)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_mesh_import_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_import_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_import_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_import_all.setObjectName("button_mesh_import_all")
        self.gridLayout_3.addWidget(self.button_mesh_import_all, 0, 0, 1, 1)
        self.button_mesh_remove_all = QtGui.QPushButton(self.mesh_control)
        self.button_mesh_remove_all.setMinimumSize(QtCore.QSize(100, 0))
        self.button_mesh_remove_all.setMaximumSize(QtCore.QSize(100, 16777215))
        self.button_mesh_remove_all.setObjectName("button_mesh_remove_all")
        self.gridLayout_3.addWidget(self.button_mesh_remove_all, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 10, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox1 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mesh_radio_x = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_x.setMaximumSize(QtCore.QSize(76, 16777215))
        self.mesh_radio_x.setObjectName("mesh_radio_x")
        self.horizontalLayout_4.addWidget(self.mesh_radio_x)
        self.mesh_radio_y = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_y.setObjectName("mesh_radio_y")
        self.horizontalLayout_4.addWidget(self.mesh_radio_y)
        self.mesh_radio_z = QtGui.QRadioButton(self.groupBox1)
        self.mesh_radio_z.setObjectName("mesh_radio_z")
        self.horizontalLayout_4.addWidget(self.mesh_radio_z)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.groupBox1, 0, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 1, 1, 1)
        self.button_mesh_rem_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_over.setObjectName("button_mesh_rem_over")
        self.gridLayout_4.addWidget(self.button_mesh_rem_over, 2, 1, 1, 1)
        self.button_mesh_imp_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_bellow.setObjectName("button_mesh_imp_bellow")
        self.gridLayout_4.addWidget(self.button_mesh_imp_bellow, 3, 0, 1, 1)
        self.button_mesh_rem_bellow = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_bellow.setObjectName("button_mesh_rem_bellow")
        self.gridLayout_4.addWidget(self.button_mesh_rem_bellow, 3, 1, 1, 1)
        self.button_mesh_imp_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_through.setObjectName("button_mesh_imp_through")
        self.gridLayout_4.addWidget(self.button_mesh_imp_through, 4, 0, 1, 1)
        self.button_mesh_rem_through = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_rem_through.setObjectName("button_mesh_rem_through")
        self.gridLayout_4.addWidget(self.button_mesh_rem_through, 4, 1, 1, 1)
        self.button_mesh_imp_over = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_over.setMinimumSize(QtCore.QSize(102, 0))
        self.button_mesh_imp_over.setObjectName("button_mesh_imp_over")
        self.gridLayout_4.addWidget(self.button_mesh_imp_over, 2, 0, 1, 1)
        self.button_mesh_imp_surface = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_surface.setObjectName("button_mesh_imp_surface")
        self.gridLayout_4.addWidget(self.button_mesh_imp_surface, 5, 0, 1, 1)
        self.button_mesh_imp_nonzero = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_imp_nonzero.setObjectName("button_mesh_imp_nonzero")
        self.gridLayout_4.addWidget(self.button_mesh_imp_nonzero, 6, 0, 1, 1)
        self.edit_mesh_crd = QtGui.QLineEdit(self.groupBox_4)
        self.edit_mesh_crd.setObjectName("edit_mesh_crd")
        self.gridLayout_4.addWidget(self.edit_mesh_crd, 1, 0, 1, 1)
        self.button_mesh_remove_zero = QtGui.QPushButton(self.groupBox_4)
        self.button_mesh_remove_zero.setObjectName("button_mesh_remove_zero")
        self.gridLayout_4.addWidget(self.button_mesh_remove_zero, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.select_mesh_mtr = QtGui.QComboBox(self.groupBox_5)
        self.select_mesh_mtr.setObjectName("select_mesh_mtr")
        self.gridLayout_6.addWidget(self.select_mesh_mtr, 0, 0, 1, 1)
        self.button_mesh_import_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_import_mtr.setMinimumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setMaximumSize(QtCore.QSize(100, 23))
        self.button_mesh_import_mtr.setObjectName("button_mesh_import_mtr")
        self.gridLayout_6.addWidget(self.button_mesh_import_mtr, 1, 0, 1, 1)
        self.button_mesh_remove_mtr = QtGui.QPushButton(self.groupBox_5)
        self.button_mesh_remove_mtr.setMinimumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setMaximumSize(QtCore.QSize(90, 23))
        self.button_mesh_remove_mtr.setObjectName("button_mesh_remove_mtr")
        self.gridLayout_6.addWidget(self.button_mesh_remove_mtr, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_3.setMinimumSize(QtCore.QSize(222, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mesh_element_id_edit = QtGui.QLineEdit(self.groupBox_3)
        self.mesh_element_id_edit.setMaximumSize(QtCore.QSize(50, 30))
        self.mesh_element_id_edit.setObjectName("mesh_element_id_edit")
        self.horizontalLayout_3.addWidget(self.mesh_element_id_edit)
        self.button_mesh_imp_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_imp_elmid.setObjectName("button_mesh_imp_elmid")
        self.horizontalLayout_3.addWidget(self.button_mesh_imp_elmid)
        self.button_mesh_rem_elmid = QtGui.QPushButton(self.groupBox_3)
        self.button_mesh_rem_elmid.setObjectName("button_mesh_rem_elmid")
        self.horizontalLayout_3.addWidget(self.button_mesh_rem_elmid)
        self.gridLayout_3.addWidget(self.groupBox_3, 8, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.mesh_control)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.mesh_element_explorer = QtGui.QPlainTextEdit(self.groupBox_6)
        self.mesh_element_explorer.setObjectName("mesh_element_explorer")
        self.gridLayout_7.addWidget(self.mesh_element_explorer, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 9, 0, 1, 2)
        self.gridLayout_5.addWidget(self.mesh_control, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_2.setMinimumSize(QtCore.QSize(328, 543))
        self.groupBox_2.setMaximumSize(QtCore.QSize(2000, 3000))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mesh_list = QtGui.QListWidget(self.groupBox_2)
        self.mesh_list.setObjectName("mesh_list")
        self.verticalLayout_4.addWidget(self.mesh_list)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_3 = QtGui.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_save_tables = QtGui.QPushButton(self.frame_3)
        self.button_save_tables.setObjectName("button_save_tables")
        self.horizontalLayout_2.addWidget(self.button_save_tables)
        self.button_draw_charts = QtGui.QPushButton(self.frame_3)
        self.button_draw_charts.setObjectName("button_draw_charts")
        self.horizontalLayout_2.addWidget(self.button_draw_charts)
        self.button_draw_maps = QtGui.QPushButton(self.frame_3)
        self.button_draw_maps.setObjectName("button_draw_maps")
        self.horizontalLayout_2.addWidget(self.button_draw_maps)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_3)
        self.label_basic_1 = QtGui.QLabel(self.tab_2)
        self.label_basic_1.setObjectName("label_basic_1")
        self.verticalLayout.addWidget(self.label_basic_1)
        self.label_basic_2 = QtGui.QLabel(self.tab_2)
        self.label_basic_2.setObjectName("label_basic_2")
        self.verticalLayout.addWidget(self.label_basic_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_analyser_title = QtGui.QLabel(self.tab_3)
        self.label_analyser_title.setMaximumSize(QtCore.QSize(584, 16777215))
        self.label_analyser_title.setObjectName("label_analyser_title")
        self.gridLayout_10.addWidget(self.label_analyser_title, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.box_sensitivity = QtGui.QGroupBox(self.frame)
        self.box_sensitivity.setMinimumSize(QtCore.QSize(0, 186))
        self.box_sensitivity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.box_sensitivity.setObjectName("box_sensitivity")
        self.formLayout = QtGui.QFormLayout(self.box_sensitivity)
        self.formLayout.setObjectName("formLayout")
        self.radio_compare_all = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_all.setChecked(True)
        self.radio_compare_all.setObjectName("radio_compare_all")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.radio_compare_all)
        self.radio_compare_surface = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_surface.setObjectName("radio_compare_surface")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.radio_compare_surface)
        self.radio_compare_selected = QtGui.QRadioButton(self.box_sensitivity)
        self.radio_compare_selected.setObjectName("radio_compare_selected")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.radio_compare_selected)
        self.check_compare_sum = QtGui.QCheckBox(self.box_sensitivity)
        self.check_compare_sum.setObjectName("check_compare_sum")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.check_compare_sum)
        self.horizontalLayout_7.addWidget(self.box_sensitivity)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_compare = QtGui.QPushButton(self.frame_4)
        self.button_compare.setObjectName("button_compare")
        self.verticalLayout_5.addWidget(self.button_compare)
        self.button_export_csv = QtGui.QPushButton(self.frame_4)
        self.button_export_csv.setObjectName("button_export_csv")
        self.verticalLayout_5.addWidget(self.button_export_csv)
        self.spin_grade_filter = QtGui.QSpinBox(self.frame_4)
        self.spin_grade_filter.setObjectName("spin_grade_filter")
        self.verticalLayout_5.addWidget(self.spin_grade_filter)
        self.button_grade_filter = QtGui.QPushButton(self.frame_4)
        self.button_grade_filter.setObjectName("button_grade_filter")
        self.verticalLayout_5.addWidget(self.button_grade_filter)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.box_merger = QtGui.QGroupBox(self.frame)
        self.box_merger.setObjectName("box_merger")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.box_merger)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_merge = QtGui.QPushButton(self.box_merger)
        self.button_merge.setObjectName("button_merge")
        self.verticalLayout_6.addWidget(self.button_merge)
        self.label = QtGui.QLabel(self.box_merger)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.edit_merge_minval = QtGui.QLineEdit(self.box_merger)
        self.edit_merge_minval.setObjectName("edit_merge_minval")
        self.verticalLayout_6.addWidget(self.edit_merge_minval)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_7.addWidget(self.box_merger)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_10.addWidget(self.frame, 5, 0, 1, 1)
        self.table_comp_rslt = QtGui.QTableView(self.tab_3)
        self.table_comp_rslt.setObjectName("table_comp_rslt")
        self.gridLayout_10.addWidget(self.table_comp_rslt, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_processing_text = QtGui.QLabel(self.groupBox_7)
        self.label_processing_text.setObjectName("label_processing_text")
        self.verticalLayout_3.addWidget(self.label_processing_text)
        self.frame_2 = QtGui.QFrame(self.groupBox_7)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_process_all = QtGui.QPushButton(self.frame_2)
        self.button_process_all.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_process_all.setObjectName("button_process_all")
        self.horizontalLayout_6.addWidget(self.button_process_all)
        self.button_process_newonly = QtGui.QPushButton(self.frame_2)
        self.button_process_newonly.setMaximumSize(QtCore.QSize(1666666, 1666666))
        self.button_process_newonly.setObjectName("button_process_newonly")
        self.horizontalLayout_6.addWidget(self.button_process_newonly)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.progress_processing = QtGui.QProgressBar(self.groupBox_7)
        self.progress_processing.setProperty("value", 24)
        self.progress_processing.setObjectName("progress_processing")
        self.verticalLayout_3.addWidget(self.progress_processing)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 634, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_Ini_File = QtGui.QMenu(self.menuBar)
        self.menu_Ini_File.setObjectName("menu_Ini_File")
        self.menuSo_lve = QtGui.QMenu(self.menuBar)
        self.menuSo_lve.setObjectName("menuSo_lve")
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_Basic_problem = QtGui.QAction(MainWindow)
        self.action_Basic_problem.setObjectName("action_Basic_problem")
        self.action_Generate_materials = QtGui.QAction(MainWindow)
        self.action_Generate_materials.setObjectName("action_Generate_materials")
        self.action_Quick_Test = QtGui.QAction(MainWindow)
        self.action_Quick_Test.setObjectName("action_Quick_Test")
        self.actionSave_Material = QtGui.QAction(MainWindow)
        self.actionSave_Material.setObjectName("actionSave_Material")
        self.actionExit_program = QtGui.QAction(MainWindow)
        self.actionExit_program.setObjectName("actionExit_program")
        self.actionSensitivity_task = QtGui.QAction(MainWindow)
        self.actionSensitivity_task.setObjectName("actionSensitivity_task")
        self.actionMonte_Carlo = QtGui.QAction(MainWindow)
        self.actionMonte_Carlo.setObjectName("actionMonte_Carlo")
        self.menu_Ini_File.addAction(self.action_Open)
        self.menu_Ini_File.addAction(self.action_Close)
        self.menu_Ini_File.addAction(self.action_Save)
        self.menu_Ini_File.addSeparator()
        self.menu_Ini_File.addAction(self.actionExit)
        self.menuSo_lve.addAction(self.action_Basic_problem)
        self.menuSo_lve.addAction(self.actionSensitivity_task)
        self.menuSo_lve.addAction(self.actionMonte_Carlo)
        self.menuTools.addAction(self.action_Quick_Test)
        self.menuTools.addAction(self.actionSave_Material)
        self.menuTools.addAction(self.actionExit_program)
        self.menuBar.addAction(self.menu_Ini_File.menuAction())
        self.menuBar.addAction(self.menuSo_lve.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.button_quick_test.setToolTip(QtGui.QApplication.translate("MainWindow", "Open last problem", None, QtGui.QApplication.UnicodeUTF8))
        self.button_quick_test.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Open last problem", None, QtGui.QApplication.UnicodeUTF8))
        self.button_quick_test.setText(QtGui.QApplication.translate("MainWindow", "Quick Start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "Flow.ini check and editor", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_control.setTitle(QtGui.QApplication.translate("MainWindow", "Import elements", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_import_all.setText(QtGui.QApplication.translate("MainWindow", "Import All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_remove_all.setText(QtGui.QApplication.translate("MainWindow", "Remove All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Element Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setTitle(QtGui.QApplication.translate("MainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_x.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_y.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.mesh_radio_z.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Axis coordinate", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_over.setText(QtGui.QApplication.translate("MainWindow", "Remove Over", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_bellow.setText(QtGui.QApplication.translate("MainWindow", "Import Bellow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_bellow.setText(QtGui.QApplication.translate("MainWindow", "Remove Bellow", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_through.setText(QtGui.QApplication.translate("MainWindow", "Import through", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_through.setText(QtGui.QApplication.translate("MainWindow", "Remove Through", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_over.setToolTip(QtGui.QApplication.translate("MainWindow", "Import all elements with altitude over set height", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_over.setText(QtGui.QApplication.translate("MainWindow", "Import Over ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_surface.setText(QtGui.QApplication.translate("MainWindow", "Import Surface ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_nonzero.setText(QtGui.QApplication.translate("MainWindow", "Import NonZero", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_remove_zero.setText(QtGui.QApplication.translate("MainWindow", "Remove Zero", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Element Material", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_import_mtr.setText(QtGui.QApplication.translate("MainWindow", "Import MTR", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_remove_mtr.setText(QtGui.QApplication.translate("MainWindow", "Remove MTR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Element ID", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_imp_elmid.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.button_mesh_rem_elmid.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Element explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "0 elemets in the list", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Element Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Basic Problem Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_tables.setText(QtGui.QApplication.translate("MainWindow", "Save Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.button_draw_charts.setText(QtGui.QApplication.translate("MainWindow", "Draw Charts", None, QtGui.QApplication.UnicodeUTF8))
        self.button_draw_maps.setText(QtGui.QApplication.translate("MainWindow", "Draw Maps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_basic_1.setText(QtGui.QApplication.translate("MainWindow", "Found 1000 elements with non-zero concentrations.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_basic_2.setText(QtGui.QApplication.translate("MainWindow", "5 elements selected for chart draw.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Basic  Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_analyser_title.setText(QtGui.QApplication.translate("MainWindow", " Monte Carlo, Sensitivity Task", None, QtGui.QApplication.UnicodeUTF8))
        self.box_sensitivity.setTitle(QtGui.QApplication.translate("MainWindow", "Compare with original task", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_compare_all.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_compare_surface.setText(QtGui.QApplication.translate("MainWindow", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_compare_selected.setText(QtGui.QApplication.translate("MainWindow", "Selected ", None, QtGui.QApplication.UnicodeUTF8))
        self.check_compare_sum.setText(QtGui.QApplication.translate("MainWindow", "Sum of Concentrations", None, QtGui.QApplication.UnicodeUTF8))
        self.button_compare.setText(QtGui.QApplication.translate("MainWindow", "Start comparsion", None, QtGui.QApplication.UnicodeUTF8))
        self.button_export_csv.setText(QtGui.QApplication.translate("MainWindow", "Export to CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.button_grade_filter.setText(QtGui.QApplication.translate("MainWindow", "Filter grade", None, QtGui.QApplication.UnicodeUTF8))
        self.box_merger.setTitle(QtGui.QApplication.translate("MainWindow", "Merge data", None, QtGui.QApplication.UnicodeUTF8))
        self.button_merge.setText(QtGui.QApplication.translate("MainWindow", "Merge Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "minimal value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Comparative Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_processing_text.setText(QtGui.QApplication.translate("MainWindow", "Found 320 tasks to analyze. Data processing will cost aprox. 90 minutes.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_process_all.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_process_newonly.setText(QtGui.QApplication.translate("MainWindow", "Unprocessed only", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Data processing", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Ini_File.setTitle(QtGui.QApplication.translate("MainWindow", "&Task File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSo_lve.setTitle(QtGui.QApplication.translate("MainWindow", "Analyser type", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Basic_problem.setText(QtGui.QApplication.translate("MainWindow", "&Basic problem", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Generate_materials.setText(QtGui.QApplication.translate("MainWindow", "&Generate materials", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quick_Test.setText(QtGui.QApplication.translate("MainWindow", "&Quick Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Material.setText(QtGui.QApplication.translate("MainWindow", "Save Material", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_program.setText(QtGui.QApplication.translate("MainWindow", "Exit program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSensitivity_task.setText(QtGui.QApplication.translate("MainWindow", "Sensitivity task", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMonte_Carlo.setText(QtGui.QApplication.translate("MainWindow", "Monte Carlo", None, QtGui.QApplication.UnicodeUTF8))

